name: Move DevBranch code to ProdBranch repository

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_directory: 'Code'
        destination_repo: 'narenderSmartData/ProdBranch'
        destination_folder: 'Code'
        user_email: 'narender.ramadheni@smartdataglobal.in'
        user_name: 'narenderSmartData'
        commit_message: 'Moved from DevBranch to ProdBranch'
